spring:
  application:
    name: ms-account
  datasource:
    url: jdbc:postgresql://postgres:5432/account_db
    username: \${DB_USER:unitech}
    password: \${DB_PASS:password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: rabbitmq
    port: 5672

server:
  port: 8082
