server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/account_db
    username: ${DB_USER:unitech}
    password: ${DB_PASS:password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

app:
  account:
    rabbitmq:
      exchange: account.exchange
      routing-key:
        created: account.created
        status-changed: account.status.changed

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    com.unitech.account.controller: DEBUG

