spring:
  application:
    name: ms-auth
  datasource:
    url: jdbc:postgresql://postgres:5432/auth_db
    username: \${DB_USER:unitech}
    password: \${DB_PASS:password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: rabbitmq
    port: 5672
  data:
    redis:
      host: redis
      port: 6379

server:
  port: 8081

jwt:
  secret: localhost8080JWTSecret
  expiration: 3600
