spring:
  application:
    name: ms-bff
  config:
    import: "optional:configserver:http://localhost:8888"
  data:
    redis:
      host: redis
      port: 6379

server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info
