server:
  port: 8084

spring:
  application:
    name: ms-currency

  # ← DATASOURCE FOR JPA
  datasource:
    url: jdbc:postgresql://localhost:5432/currency_db
    username: unitech
    password: password 
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update    # or "create" if you want a fresh schema each run
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

currency:
  api:
    url: https://api.exchangeratesapi.io/v1
    access-key: 2fa78b9520eeb3e802b5fb420a45dff3
    cache-ttl-seconds: 3600
