server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: auth-service
          uri: lb://ms-auth
          predicates:
            - Path=/api/auth/**
        - id: ms-account
          uri: lb://ms-account    
          predicates:
            - Path=/api/account/**
  redis:
    host: localhost
    port: 6379

jwt:
  secret: 9a995e2cbc1982886f08f8a933de90bceb080acbf0a7b434aca758d89aa7aa549d14336a422e659a81d4144d7c73bafacc75b8003ed38953919320a1df8d4296
  expiration: 3600

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.server: DEBUG
