server:
  port: 8083

spring:
  application:
    name: ms-transfer
  cloud:
    discovery:
      enabled: true
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
          
  datasource:
    url: jdbc:postgresql://localhost:5432/transfer_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

rabbitmq:
  host: localhost
  port: 5672

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
