server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/transfer_db
    username: ${DB_USER:unitech}
    password: ${DB_PASS:password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

rabbitmq:
  host: rabbitmq
  port: 5672

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info
